import unicode_codigos
import unicode_combinaciones

import gendef

def filtra_grupo(caracteres, inicial, final, pagina):
    resultado = []
    for c in caracteres:
        if int(c[gendef.UCO][0], 16) >= int(inicial, 16) and int(c[gendef.UCO][0], 16) <= int(final, 16):
            resultado += [c]

    resultado2 = []
    for c in resultado:
        # Esto filtra los caracteres que simplemente no quiero ver en ningún caso
        if pagina == gendef.PAG_SIMBOLOS:
            if c[gendef.VS] != "" or c[gendef.TWE] == "":
                resultado2 += [c]
        elif pagina == gendef.PAG_EMOJIS:
            if c[gendef.VS] != "" or c[gendef.TWE] == "TWE":
                resultado2 += [c]
    return resultado2

grupos = {
    gendef.PAG_SIMBOLOS: [
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "0000", "007F", gendef.PAG_SIMBOLOS),
            "Controles y Latin básico",
            "controles-latin",
            "U00000-c0-controls-and-basic-latin.pdf",
            1,
            "0000",
            "007F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "0080", "00FF", gendef.PAG_SIMBOLOS),
            "Suplemento controles y Latin-1",
            "controles-sup",
            "U00080-c1-controls-and-latin-1-supplement.pdf",
            1,
            "0080",
            "00FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2000", "206F", gendef.PAG_SIMBOLOS),
            "Puntuación",
            "puntuacion",
            "U02000-general-punctuation.pdf",
            1,
            "2000",
            "206F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "20A0", "20BF", gendef.PAG_SIMBOLOS),
            "Símbolos de monedas",
            "monedas",
            "U020A0-currency-symbols.pdf",
            1,
            "20A0",
            "20BF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2100", "214F", gendef.PAG_SIMBOLOS),
            "Símbolos con letras",
            "simbolos-letras",
            "U02100-letterlike-symbols.pdf",
            1,
            "2100",
            "214F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2190", "21FF", gendef.PAG_SIMBOLOS),
            "Flechas",
            "flechas",
            "U02190-arrows.pdf",
            1,
            "2190",
            "21FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2300", "23FE", gendef.PAG_SIMBOLOS),
            "Símbolos técnicos misceláneos",
            "tecnicos-misc",
            "U02300-miscellaneous-technical.pdf",
            1,
            "2300",
            "23FE",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2460", "24FF", gendef.PAG_SIMBOLOS),
            "Símbolos alfanuméricos con círculo alrededor",
            "alfanum-circulo",
            "U02460-enclosed-alphanumerics.pdf",
            1,
            "2460",
            "24FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2500", "257F", gendef.PAG_SIMBOLOS),
            "Cajas",
            "cajas",
            "U02500-box-drawing.pdf",
            1,
            "2500",
            "257F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "25A0", "25FF", gendef.PAG_SIMBOLOS),
            "Formas geométricas",
            "formas-geometricas",
            "U025A0-geometric-shapes.pdf",
            1,
            "25A0",
            "25FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2600", "26FF", gendef.PAG_SIMBOLOS),
            "Símbolos misceláneos",
            "simbolos-misc",
            "U02600-miscellaneous-symbols.pdf",
            1,
            "2600",
            "26FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2700", "27BF", gendef.PAG_SIMBOLOS),
            "Dingbats",
            "dingbats",
            "U02700-dingbats.pdf",
            1,
            "2700",
            "27BF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2900", "297F", gendef.PAG_SIMBOLOS),
            "Flechas suplementarias B",
            "flechas-suplementarias",
            "U02900-supplemental-arrows-b.pdf",
            1,
            "2900",
            "297F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2B00", "2BFF", gendef.PAG_SIMBOLOS),
            "Símbolos y flechas misceláneos",
            "simbolos-flechas",
            "U02B00-miscellaneous-symbols-and-arrows.pdf",
            1,
            "2B00",
            "2BFF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "3000", "303F", gendef.PAG_SIMBOLOS),
            "Símbolos y puntuación CJK",
            "cjk",
            "U03000-cjk-symbols-and-punctuation.pdf",
            1,
            "3000",
            "303F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "3200", "32FF", gendef.PAG_SIMBOLOS),
            "Símbolos CJK con círculo alrededor",
            "cjk-circulo",
            "U03200-enclosed-cjk-letters-and-months.pdf",
            1,
            "3200",
            "32FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1D100", "1D1E8", gendef.PAG_SIMBOLOS),
            "Símbolos musicales",
            "musica",
            "U1D100-musical-symbols.pdf",
            1,
            "1D100",
            "1D1E8",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F000", "1F02B", gendef.PAG_SIMBOLOS),
            "Fichas de Mahjong",
            "fichas-mahjong",
            "U1F000-mahjong-tiles.pdf",
            1,
            "1F000",
            "1F02B",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F030", "1F093", gendef.PAG_SIMBOLOS),
            "Fichas de dominó",
            "domino",
            "U1F030-domino-tiles.pdf",
            1,
            "1F030",
            "1F093",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F0A0", "1F0F5", gendef.PAG_SIMBOLOS),
            "Cartas",
            "cartas",
            "U1F0A0-playing-cards.pdf",
            1,
            "1F0A0",
            "1F0F5",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F100", "1F1FF", gendef.PAG_SIMBOLOS),
            "Suplemento alfanuméricos con círculo alrededor",
            "alfanum-circulo-sup",
            "U1F100-enclosed-alphanumeric-supplement.pdf",
            1,
            "1F100",
            "1F1FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F200", "1F2FF", gendef.PAG_SIMBOLOS),
            "Suplemento ideográfico con círculo alrededor",
            "ideografico-circulo-sup",
            "U1F200-enclosed-ideographic-supplement.pdf",
            1,
            "1F200",
            "1F2FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F650", "1F67F", gendef.PAG_SIMBOLOS),
            "Dingbats decorativos",
            "dingbats-decorativos",
            "U1F650-ornamental-dingbats.pdf",
            1,
            "1F650",
            "1F67F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F700", "1F773", gendef.PAG_SIMBOLOS),
            "Símbolos alquímicos",
            "simbolos-alquimicos",
            "U1F700-alchemical-symbols.pdf",
            1,
            "1F700",
            "1F773",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F780", "1F7EB", gendef.PAG_SIMBOLOS),
            "Formas geométricas extendidas",
            "geometricas-extendidas",
            "U1F780-geometric-shapes-extended.pdf",
            1,
            "1F780",
            "1F7EB",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F300", "1F5FF", gendef.PAG_SIMBOLOS),
            "Símbolos y pictogramas misceláneos",
            "simbolos-pict-misc",
            "U1F300-miscellaneous-symbols-and-pictographs.pdf",
            1,
            "1F300",
            "1F5FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F600", "1F64F", gendef.PAG_SIMBOLOS),
            "Emoticonos",
            "emoticonos",
            "U1F600-emoticons.pdf",
            1,
            "1F600",
            "1F64F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F680", "1F6FF", gendef.PAG_SIMBOLOS),
            "Símbolos de transporte y mapas",
            "transporte",
            "U1F680-transport-and-map-symbols.pdf",
            1,
            "1F680",
            "1F6FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F900", "1F9FF", gendef.PAG_SIMBOLOS),
            "Símbolos y pictogramas misceláneos suplementarios",
            "simbolos-misc-supl",
            "U1F900-supplemental-symbols-and-pictographs.pdf",
            1,
            "1F900",
            "1F9FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1FA70", "1FAFF", gendef.PAG_SIMBOLOS),
            "Símbolos y pictogramas extendidos A",
            "simbolos-ext-a",
            "U1FA70-symbols-and-pictographs-extended-a.pdf",
            1,
            "1FA70",
            "1FAFF",
        ],
    ],
    gendef.PAG_EMOJIS: [
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "0000", "007F", gendef.PAG_EMOJIS),
            "Controles y Latin básico",
            "controles-latin",
            "U00000-c0-controls-and-basic-latin.pdf",
            1,
            "0000",
            "007F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "0080", "00FF", gendef.PAG_EMOJIS),
            "Suplemento controles y Latin-1",
            "controles-sup",
            "U00080-c1-controls-and-latin-1-supplement.pdf",
            1,
            "0080",
            "00FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2000", "206F", gendef.PAG_EMOJIS),
            "Puntuación",
            "puntuacion",
            "U02000-general-punctuation.pdf",
            1,
            "2000",
            "206F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "20A0", "20BF", gendef.PAG_EMOJIS),
            "Símbolos de monedas",
            "monedas",
            "U020A0-currency-symbols.pdf",
            1,
            "20A0",
            "20BF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2100", "214F", gendef.PAG_EMOJIS),
            "Símbolos con letras",
            "simbolos-letras",
            "U02100-letterlike-symbols.pdf",
            1,
            "2100",
            "214F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2190", "21FF", gendef.PAG_EMOJIS),
            "Flechas",
            "flechas",
            "U02190-arrows.pdf",
            1,
            "2190",
            "21FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2300", "23FE", gendef.PAG_EMOJIS),
            "Símbolos técnicos misceláneos",
            "tecnicos-misc",
            "U02300-miscellaneous-technical.pdf",
            1,
            "2300",
            "23FE",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2460", "24FF", gendef.PAG_EMOJIS),
            "Símbolos alfanuméricos con círculo alrededor",
            "alfanum-circulo",
            "U02460-enclosed-alphanumerics.pdf",
            1,
            "2460",
            "24FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2500", "257F", gendef.PAG_EMOJIS),
            "Cajas",
            "cajas",
            "U02500-box-drawing.pdf",
            1,
            "2500",
            "257F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "25A0", "25FF", gendef.PAG_EMOJIS),
            "Formas geométricas",
            "formas-geometricas",
            "U025A0-geometric-shapes.pdf",
            1,
            "25A0",
            "25FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2600", "26FF", gendef.PAG_EMOJIS),
            "Símbolos misceláneos",
            "simbolos-misc",
            "U02600-miscellaneous-symbols.pdf",
            1,
            "2600",
            "26FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2700", "27BF", gendef.PAG_EMOJIS),
            "Dingbats",
            "dingbats",
            "U02700-dingbats.pdf",
            1,
            "2700",
            "27BF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2900", "297F", gendef.PAG_EMOJIS),
            "Flechas suplementarias B",
            "flechas-suplementarias",
            "U02900-supplemental-arrows-b.pdf",
            1,
            "2900",
            "297F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "2B00", "2BFF", gendef.PAG_EMOJIS),
            "Símbolos y flechas misceláneos",
            "simbolos-flechas",
            "U02B00-miscellaneous-symbols-and-arrows.pdf",
            1,
            "2B00",
            "2BFF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "3000", "303F", gendef.PAG_EMOJIS),
            "Símbolos y puntuación CJK",
            "cjk",
            "U03000-cjk-symbols-and-punctuation.pdf",
            1,
            "3000",
            "303F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "3200", "32FF", gendef.PAG_EMOJIS),
            "Símbolos CJK con círculo alrededor",
            "cjk-circulo",
            "U03200-enclosed-cjk-letters-and-months.pdf",
            1,
            "3200",
            "32FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1D100", "1D1E8", gendef.PAG_EMOJIS),
            "Símbolos musicales",
            "musica",
            "U1D100-musical-symbols.pdf",
            1,
            "1D100",
            "1D1E8",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F000", "1F02B", gendef.PAG_EMOJIS),
            "Fichas de Mahjong",
            "fichas-mahjong",
            "U1F000-mahjong-tiles.pdf",
            1,
            "1F000",
            "1F02B",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F030", "1F093", gendef.PAG_EMOJIS),
            "Fichas de dominó",
            "domino",
            "U1F030-domino-tiles.pdf",
            1,
            "1F030",
            "1F093",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F0A0", "1F0F5", gendef.PAG_EMOJIS),
            "Cartas",
            "cartas",
            "U1F0A0-playing-cards.pdf",
            1,
            "1F0A0",
            "1F0F5",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F100", "1F1FF", gendef.PAG_EMOJIS),
            "Suplemento alfanuméricos con círculo alrededor",
            "alfanum-circulo-sup",
            "U1F100-enclosed-alphanumeric-supplement.pdf",
            1,
            "1F100",
            "1F1FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F200", "1F2FF", gendef.PAG_EMOJIS),
            "Suplemento ideográfico con círculo alrededor",
            "ideografico-circulo-sup",
            "U1F200-enclosed-ideographic-supplement.pdf",
            1,
            "1F200",
            "1F2FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F650", "1F67F", gendef.PAG_EMOJIS),
            "Dingbats decorativos",
            "dingbats-decorativos",
            "U1F650-ornamental-dingbats.pdf",
            1,
            "1F650",
            "1F67F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F700", "1F773", gendef.PAG_EMOJIS),
            "Símbolos alquímicos",
            "simbolos-alquimicos",
            "U1F700-alchemical-symbols.pdf",
            1,
            "1F700",
            "1F773",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F780", "1F7EB", gendef.PAG_EMOJIS),
            "Formas geométricas extendidas",
            "geometricas-extendidas",
            "U1F780-geometric-shapes-extended.pdf",
            1,
            "1F780",
            "1F7EB",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F300", "1F5FF", gendef.PAG_EMOJIS),
            "Símbolos y pictogramas misceláneos",
            "simbolos-pict-misc",
            "U1F300-miscellaneous-symbols-and-pictographs.pdf",
            1,
            "1F300",
            "1F5FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F600", "1F64F", gendef.PAG_EMOJIS),
            "Emoticonos",
            "emoticonos",
            "U1F600-emoticons.pdf",
            1,
            "1F600",
            "1F64F",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F680", "1F6FF", gendef.PAG_EMOJIS),
            "Símbolos de transporte y mapas",
            "transporte",
            "U1F680-transport-and-map-symbols.pdf",
            1,
            "1F680",
            "1F6FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1F900", "1F9FF", gendef.PAG_EMOJIS),
            "Símbolos y pictogramas misceláneos suplementarios",
            "simbolos-misc-supl",
            "U1F900-supplemental-symbols-and-pictographs.pdf",
            1,
            "1F900",
            "1F9FF",
        ],
        [
            filtra_grupo(unicode_codigos.caracteres_unicode, "1FA70", "1FAFF", gendef.PAG_EMOJIS),
            "Símbolos y pictogramas extendidos A",
            "simbolos-ext-a",
            "U1FA70-symbols-and-pictographs-extended-a.pdf",
            1,
            "1FA70",
            "1FAFF",
        ],
    ],
    # Secuencias de Variación
    "Variación": [
        [unicode_combinaciones.variacion, "Secuencias de variación", "variacion", "", 1, "00000", "1FAFF"],
    ],
    # Banderas
    "Secuencias_1": [
        [unicode_combinaciones.cu_banderas, "Banderas", "banderas", "", 0, "", ""],
        [unicode_combinaciones.cu_banderas_sub, "Banderas (subdivisiones)", "banderas-2", "", 0, "", ""],
    ],
    # Géneros que funcionan en Windows y en Twemoji
    "Secuencias_2": [
        [unicode_combinaciones.genero_1, "Género (1)", "genero-1", "", 0, "", "", ["ss", "te"]],
        [unicode_combinaciones.genero_2, "Género (2)", "genero-2", "", 0, "", "", ["ss", "te"]],
        # CUIDADO problematicas_piel_1 están separados de genero_3 porque al poner colores de piel no salen bien en Windows
        # Lo que me faltaría es ordenar los elementos, porque ahora se añaden al final
        # pero no tengo claro cómo ordenar matrices multidimensionales https://www.php.net/manual/es/def.array-multisort.php
        [
            unicode_combinaciones.genero_3 + unicode_combinaciones.problematicas_piel_1,
            "Género (3)",
            "genero-3",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [unicode_combinaciones.genero_4, "Género (4)", "genero-4", "", 0, "", "", ["ss", "te"]],
        #  ["Colores de piel",                                     "colores-piel",    "", 0, "0261D", "1F9FF"],
        #  ["Otros",                                               "otros",           "", 4, "0002A", "1F4FF"],
    ],
    # Colores de piel que funcionan en Windows y en Twemoji
    "Secuencias_3": [
        [unicode_combinaciones.piel_1, "Colores de piel (1)", "colores-piel-1", "", 0, "", "", ["ss", "te"]],
        [
            unicode_combinaciones.genero_1,
            "Colores de piel (2)",
            "colores-piel-2",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.genero_2,
            "Colores de piel (3)",
            "colores-piel-3",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.genero_3,
            "Colores de piel (4)",
            "colores-piel-4",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
    ],
    # Parejas y familias
    "Secuencias_4": [
        [unicode_combinaciones.cu_familias, "Familias", "familias", "", 0, "", ""],
        [unicode_combinaciones.cu_parejas_1, "Parejas de enamorados", "parejas-1", "", 0, "", ""],
        [unicode_combinaciones.cu_parejas_2, "Parejas de enamorados besándose", "parejas-2", "", 0, "", ""],
        [
            unicode_combinaciones.cu_parejas_piel_1,
            "Parejas neutras y colores de piel",
            "parejas-piel-1",
            "",
            0,
            "",
            "",
        ],
        [
            unicode_combinaciones.cu_parejas_piel_2,
            "Parejas con género y colores de piel",
            "parejas-piel-2",
            "",
            0,
            "",
            "",
        ],
    ],
    "Secuencias_problematicas_1": [
        [
            unicode_combinaciones.problematicas_otros,
            "Varios",
            "varios-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
    ],
    # Géneros que NO funcionan en Windows o en Twemoji
    "Secuencias_problematicas_2": [
        [
            unicode_combinaciones.problematicas_genero_1,
            "Género (1)",
            "genero-1-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_genero_2,
            "Género (2)",
            "genero-2-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_genero_3,
            "Género (3)",
            "genero-3-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_genero_4,
            "Género (4)",
            "genero-4-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
    ],
    # Colores de piel que NO funcionan en Windows o en Twemoji
    "Secuencias_problematicas_3": [
        [
            unicode_combinaciones.problematicas_piel_1,
            "Colores de piel (1)",
            "colores-piel-1-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_piel_2,
            "Colores de piel (2)",
            "colores-piel-2-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_piel_3,
            "Colores de piel (3)",
            "colores-piel-3-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
        [
            unicode_combinaciones.problematicas_piel_4,
            "Colores de piel (4)",
            "colores-piel-4-problemas",
            "",
            0,
            "",
            "",
            ["ss", "te"],
        ],
    ],
}
